### ISSUE TITLE
Device Environment Variable Endpoint No Filters / Updates

### ISSUE THREAD

**Issue by panbanda** [balena-io/open-balena-api#733]
I am using the latest BalenaOS + openBalena and am currently trying to update my environment variables using this method.

My request looks like this:

```
curl --request PUT \
  --url "https://api.<URL>/v6/device_environment_variable(device='DEVICE_ID',name='whoa')" \
  --header 'Authorization: Bearer XXXXXXXXXXX' \
  --header 'Content-Type: application/json' \
  --data '{"value": "todayz"}'
```

When I run this command I am getting the error: “Can only call getAffectedIds with PATCH/DELETE requests”.  

The same endpoint also does not filter, makes me think there is a larger issue?

```
# Lists all the environment variables
https://api.<URL>/v6/device_environment_variable

# Lists all, but should not list any as "fds" doesn't exist (this is the former format I used and it worked)
https://api.<URL>/v6/device_environment_variable?\$filter=uuid%20eq%20'fds'

# Lists all, but should not list any as "fds" doesn't exist (this is the API documentation below)
https://api.<URL>/v6/device_environment_variable?\$filter=device%20eq%20'fds'
```

However, I am following the documentation outlined below:

https://www.balena.io/docs/reference/api/resources/device_environment_variable/

**Comment by thgreasi** [comment]
Hi @panbanda,
We currently do not currently officially support PUT requests on our API.
Even though you might be able to find some endpoints that seem to work with PUT requests, on the cloud API we have completely prohibited them, which arguably we should also do in open-balena so that there is less confusion.

Atm you will have to do a POST first and then do a PATCH in case you get back a conflict error. Let me point you to how our js client does that:
See: https://github.com/balena-io-modules/pinejs-client-js/blob/61aa461c3ef4cd20e59f4f346bdac714bf18baa5/src/index.ts#L1078-L1079


As for your your question about filtering I see to (potential) issues:
* the device uuid is not a property available on the `device_environment_variable` resource, and I would expect this request to return and internal server error
* I'm suspecting that your escaping of the `$filter` might be wrong, which explains why your uuid based query doesn't error.

Can you give the following curl a try?
```
curl 'https://api.balena-cloud.com/v6/device_environment_variable?$filter=device%20eq%201234' \
  -H 'authorization: Bearer <TOKEN>'
```

**Comment by panbanda** [comment]
Thanks @thgreasi for the fast response. That looks like the issue-- I kind of get confused in docs when ids are interchangeable and uuids are required vs integers.  The integer worked so I can definitely use that.  

I can do the post and patch.  No problem.  I remember seeing a thread about the request taking 10+ seconds and so PUT requests we're prohibited.  I also thought it was just on the hosted version not on openbalena.  

Appreciate it!
