### ISSUE TITLE
Device `overall_status` fluctuates between `idle` and `updating` during updates

### ISSUE THREAD

**Issue by cywang117** [balena-io/open-balena-api#923]
Expected: `overall_status` should stay on `updating` when device is updating.
Actual: `overall_status` was observed to fluctuate between `updating` and `idle`.

**Comment by thgreasi** [comment]
@cywang117 are you sure this is an API issue?
The computed term only returns `idle` when there is no  image install w/ non-null download progress & `Downloading` status.
See: https://github.com/balena-io/open-balena-api/blob/5d5c7a13c350bdbe80003990cbd28e148815f7a2/src/features/devices/models/device-additions.ts#L158

An alternative theory could be that the issue comes from the way we do throttle updating image installs in the API, but that as well seems fine.
See: https://github.com/balena-io/open-balena-api/blob/5d5c7a13c350bdbe80003990cbd28e148815f7a2/src/features/device-state/routes/state-patch.ts#L295-L301

I've seen this in the dashboard before, and it was many times the case that the supervisor hadn't yet created all image installs.
It would be great if we had some logs w/ the state patches that lead to this case.

**Comment by cywang117** [comment]
@thgreasi I'll take a look at getting some logs and seeing if I can reproduce this. Thanks for the info!

**Comment by cywang117** [comment]
Gathered some state patch logs from a reproduction I'd set up. The circumstances were that a balenaFin was updating to balenaSound. See [here](https://gist.github.com/cywang117/8a8c05f09fc3e3f7d71aeece9922a9e6) for complete logs. I observed the device's `overall_status` switching briefly from `updating` to `idle` [here](https://gist.github.com/cywang117/8a8c05f09fc3e3f7d71aeece9922a9e6#file-state-patch-logs-overall-status-L491-L568), when a state patch did not include a status of `Downloading` or any non-null `download_progress` fields. Rather, the state diff at that time changed 2 services from `Downloading` to `Downloaded`. 

After a few more state reports, the remaining services started downloading, until completion. From these logs, it looks either the Supervisor or the engine spreads out the container downloads over a period of time. At some point during this period of time, a state PATCH was issued when when no service were downloading. I do think this is reasonable behavior from the POV of the Supervisor -- after all, the status of the device at the time is in fact one where no containers are downloading.  

If a change were necessary for better UX of `overall_status` reporting, I'm leaning towards an API change that ensures all services have exited `Downloading` status before `overall_status` changes back to `idle`. @thgreasi Do you think such a change is necessary? Technically the API and Supervisor are both reporting the truth here..

**Comment by thgreasi** [comment]
@cywang117 this wouldn't have been an issue if the supervisor was creating all image installs for the new release upfront. We had thought before that the API should have been the one creating all those upfront, hence controlling the whole process, but the blocker was that we can't know for sure whether the supervisor will be creating/downloading all images of the release, since there might be a release contract stating that some of the containers shouldn't run on that device, and the API can't reason about such cases. A different phenotype of this same underlying issue, is that the progress % some times also decreases, which happens when the supervisor has just created an additional image install on 0% out of sync with the previous ones.

**Comment by cywang117** [comment]
Closing in favor of https://github.com/balena-os/balena-supervisor/issues/1870

**Comment by cywang117** [comment]
Thanks for the feedback @thgreasi !

**Comment by thgreasi** [comment]
It's great working with you @cywang117 :)
